
class ActionTypes {

    // Authentication
    static SIGNUP = 'SIGNUP';
    static SIGNUP_SUCCESS = 'SIGNUP_LANDLORD_SUCCESS';
    static SIGNUP_FAILURE = 'SIGNUP_FAILURE';

    static CONFIRM = 'CONFIRM';
    static CONFIRM_SUCCESS = 'CONFIRM_SUCCESS';
    static CONFIRM_FAILURE = 'CONFIRM_FAILURE';

    static SIGNIN = 'SIGNIN';
    static SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
    static SIGNIN_FAILURE = 'SIGNIN_FAILURE';

    static GET_DATA = 'GET_DATA';
    static GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
    static GET_DATA_FAIL = 'GET_DATA_FAIL';

    static GET_MID_DATA = 'GET_MID_DATA';
    static GET_MID_DATA_SUCCESS = 'GET_MID_DATA_SUCCESS';
    static GET_MID_DATA_FAILED = 'GET_MID_DATA_FAILED';

    static LOGIN = 'LOGIN';
    static LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    static LOGIN_FAILED = 'LOGIN_FAILED';

    static SEND_EMAIL_MESSAGE = 'SEND_EMAIL_MESSAGE';
    static SEND_EMAIL_MESSAGE_SUCCESS = 'SEND_EMAIL_MESSAGE_SUCCESS';
    static SEND_EMAIL_MESSAGE_FAILED = 'SEND_EMAIL_MESSAGE_FAILED';
    
};

export { ActionTypes };